rtsp_url: "rtsp://falt:panofalt1234@77.232.155.123:556"
ip_interior: "192.168.0.168"
login: "falt"
password: "panofalt1234"
ip_external: "77.232.155.123"
web_interface: "77.232.155.123:16455"

model_path: "yolov8n.pt"

confidence: 0.4
skip_frames: 1
scale: 0.5

save_path: "output.mp4"